dataground/nginx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
]

dataground/services/urls.py
from django.urls import include, path, re_path
from . import views
from django.conf.urls.static import static
from config.settings import base

app_name = 'services'


urlpatterns =[
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('map_log/', views.match_log_map, name='map_log'),
    path('maps/', views.map_analysis, name='maps'),
    path('weapons/', views.weapon_analysis, name='weapons'),
    path('getMapImageURL', views.get_map_image_url, name='get_map_image_url'),
    path('weapons_detail/<str:weapon_name>/', views.weapons_detail, name='weapons_detail')
 ]

if base.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

dataground/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <meta charset="UTF-8">
</head>
<body>
    <img class="word-cloud" src="{% static 'word_cloud.png' %}" alt="Word Cloud">
    <div class="button-form-wrapper">
        <button id="serviceButton">Steam</button>
        <form class="user_search" id="searchForm" method="GET" action="{% url 'services:profile' %}">
            <input type="hidden" id="serviceNameInput" name="service" value="steam">
            <input type="text" id="userNameInput" name="user_name" placeholder="유저 이름" value="">
            <button id="searchButton" type="submit" disabled>검색</button>
        </form>
    </div>

    <br>
    <br>
    <div class="menuButton-wrapper">
        <a href="{% url 'services:weapons' %}">
            <button class="menuButton" id="weaponButton">무기 분석</button>
        </a>
        <a href="{% url 'services:maps' %}">
            <button class="menuButton" id="mapButtom">맵 분석</button>
        </a>
    </div>

    <script src="{% static 'main.js' %}"></script>
</body>
</html>

dataground/templates/map.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>지도</title>
    <link rel="stylesheet" type="text/css" href="https:///unpkg.com/leaflet/dist/leaflet.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}" />
    <script src="https:///unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
    <div class="container">
        <div id="map"></div>
        <div class="info-panel">
            <div class="header-container">
                <h2>Kills 정보 (이동 경로는 시간 경과에 따라 초록색에서 빨간색으로 변합니다.)</h2>
                <button onclick="goBack()" class="back-btn">뒤로가기 ↩︎</button>
            </div>
            <!-- Kills 정보를 나열할 영역을 추가하세요 -->
            <ul>
                {% for kill in kills %}
                    {% if kill.killer_name == player_name %}
                        <li class="kill-box">
                            <span class="event-time">{{ kill.event_time|seconds_to_mins_secs }}</span> {{ kill.victim_name }} 킬  {% if 'ai.' in kill.victim_account_id %} <span class="ai-text">(AI)</span>{% endif %}
                            <span class="kill-count">{{ forloop.counter }}킬</span>
                        </li>
                    {% elif kill.victim_name == player_name %}
                        <li class="death-box">
                            <span class="event-time">{{ kill.event_time|seconds_to_mins_secs }}</span> {{ kill.killer_name }} 에게 죽음
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            var imageUrl = '{% static "maps/" %}' + '{{ map_name }}' + '_log.jpg';
            var player_name = '{{ player_name }}';
    
            var image = new Image();
            image.src = imageUrl;
    
            image.onload = function () {
                var width = image.width;
                var height = image.height;
    
                // 이미지가 맵에 꽉 차도록 비율 계산
                var aspectRatio = width / height;
                var mapWidth = 800;
                var mapHeight = mapWidth / aspectRatio;
    
                var map = L.map('map', {
                    crs: L.CRS.Simple,
                    maxBounds: [[0, 0], [mapHeight, mapWidth]],
                    maxBoundsViscosity: 1.0,
                });
    
                var bounds = [[0, 0], [mapHeight, mapWidth]];
                L.imageOverlay(imageUrl, bounds).addTo(map);
    
                map.fitBounds(bounds); // 이미지가 자동으로 보이도록 지도 확대
    
                var killerIcon = L.icon({
                    iconUrl: '{% static "icons/Gun.png" %}',
                    iconSize: [32.8, 20],
                });
    
                var victimIcon = L.icon({
                    iconUrl: '{% static "icons/Death.png" %}',
                    iconSize: [40, 28],
                });
    
                var mapSize = {% if map_name == 'Erangel' %}819200{% elif map_name == 'Miramar' %}815850{% elif map_name == 'Sanhok' %}408050{% elif map_name == 'Vikendi' %}815800{% elif map_name == 'Taego' %}815850{% elif map_name == 'Deston' %}816000{% endif %};
    
                var kills = [
                    {% for kill in kills %}
                    [
                        {{ kill.killer_x|floatformat:2 }},
                        {{ kill.killer_y|floatformat:2 }},
                        {{ kill.victim_x|floatformat:2 }},
                        {{ kill.victim_y|floatformat:2 }},
                        '{{ kill.killer_name }}',
                        '{{ kill.victim_name }}'
                    ],
                    {% endfor %}
                ];
    
                var positions = [
                    {% for position in positions %}
                    [
                        {{ position.location_x|floatformat:2 }},
                        {{ position.location_y|floatformat:2 }}
                    ],
                    {% endfor %}
                ];
    
                // 킬 정보를 사용하여 마커와 폴리라인을 추가하고 지도에 표시합니다.
                for (var i = 0; i < kills.length; i++) {
                    var adjustedKillerY = (kills[i][0] * 800) / mapSize;
                    var adjustedKillerX = 800 - ((kills[i][1] * 800) / mapSize);
                    var adjustedVictimY = (kills[i][2] * 800) / mapSize;
                    var adjustedVictimX = 800 - ((kills[i][3] * 800) / mapSize);
                    
                    L.marker([adjustedKillerX, adjustedKillerY], { icon: killerIcon }).addTo(map);
                    L.marker([adjustedVictimX, adjustedVictimY], { icon: victimIcon }).addTo(map);

                    var polylineColor = 'blue';
                    if (kills[i][5] === player_name) {
                        var polylineColor = 'purple';
                    }

                    L.polyline([
                        [adjustedKillerX, adjustedKillerY],
                        [adjustedVictimX, adjustedVictimY]
                    ], { color: polylineColor }).addTo(map);
                }

                var positionCoordinates = [];
                var colorStep = 100 / positions.length; // 색상의 변화 간격

                for (var j = 0; j < positions.length; j++) {
                    var adjustedPositionY = (positions[j][0] * 800) / mapSize;
                    var adjustedPositionX = 800 - ((positions[j][1] * 800) / mapSize);

                    var hue = 100 -(j * colorStep); // 색상 계산

                    var color = 'hsl(' + hue + ', 100%, 50%)'; // HSL 색상으로 변환

                    positionCoordinates.push([adjustedPositionX, adjustedPositionY, color]);
                }

                // 모든 좌표를 포함하는 폴리라인을 생성하고 지도에 추가합니다.
                for (var k = 0; k < positionCoordinates.length - 1; k++) {
                    L.polyline(
                        [positionCoordinates[k], positionCoordinates[k + 1]],
                        { color: positionCoordinates[k][2] }
                    ).addTo(map);
                }
            };
        });
        function goBack() {
            window.history.back();
        }
    </script>
</body>
</html>

dataground/templates/map_analysis.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    {% include 'navbar.html' %}
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="row justify-content-center">
        <div class="col-lg-8 bg-white p-4">
            <div class="map-top">
                <div class="map-button-container">
                    <button class="map-select-button" data-button-id="1" id="button1">에란겔</button>
                    <button class="map-select-button" data-button-id="2" id="button2">미라마</button>
                    <button class="map-select-button" data-button-id="3" id="button3">사녹</button>
                    <button class="map-select-button" data-button-id="4" id="button4">비켄디</button>
                    <button class="map-select-button" data-button-id="5" id="button5">테이고</button>
                    <button class="map-select-button" data-button-id="6" id="button6">데스턴</button>
                </div>
            </div>
            <div class="img-container">
                <div class="info"></div>
                <form id="map-form">
                    <div class="airplaine-direction"></div>
                    {% csrf_token %}
                </form>
                <div id="content">
                </div>
                
            </div>
        </div>
    </div>
    <script src="{% static 'map_analysis.js' %}"></script>
</body>

dataground/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:index' %}">HOME</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'services:weapons' %}">무기 분석</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'services:maps' %}">맵 분석</a>
          </li>
      </ul>
      <div class="button-form-wrapper">
          <button class="btn btn-outline-success my-2 my-sm-0" id="serviceButton">Steam</button>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'services:profile' %}">
            <input type="hidden" id="serviceNameInput" name="service" value="steam">
            <input class="form-control mr-sm-2" id="userNameInput" name="user_name" type="text" placeholder="유저 이름" value="" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
          </form>
        </div>
      </div>
    <script src="{% static 'main.js' %}"></script>
  </nav>

dataground/templates/weapon_analysis.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    {% include 'navbar.html' %}
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="row justify-content-center">
        <div class="col-lg-8 bg-white p-4">
            <div class="info" style="width: 1050px;">
                <h2>티어 선정은 <span style="color: rgb(44, 104, 254)">Top10</span> 유저들의 주 무기 사용률 입니다.<br>보급 무기는 <span style="color: purple">보라색</span>으로 표시 됩니다.</h2>
            </div>
            <!-- Tier 1 -->
            <div class="tier1-header">1티어</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_tier1 %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <!-- Tier 2 -->
            <div class="tier2-header">2티어</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_tier2 %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    <link rel="stylesheet" href="{% static 'style.css' %}">
                    {% endfor %}
                </div>
            </div>

            <!-- Tier 3 -->
            <div class="tier3-header">3티어</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_tier3 %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    <link rel="stylesheet" href="{% static 'style.css' %}">
                    {% endfor %}
                </div>
            </div>

            <!-- Tier 4 -->
            <div class="tier4-header">4티어</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_tier4 %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    <link rel="stylesheet" href="{% static 'style.css' %}">
                    {% endfor %}
                </div>
            </div>

            <!-- Tier 5 -->
                <div class="tier5-header">5티어</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_tier5 %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    <link rel="stylesheet" href="{% static 'style.css' %}">
                    {% endfor %}
                </div>
            </div>

            <!-- 표본 없음 (null값)-->
            <div class="tier-rip-header">RIP (표본 부족)</div>
            <div class="container">
                <div class="row">
                    {% for weapon in weapons_no_tier %}
                    <div class="weapon-container">
                        <a href="{% url 'services:weapons_detail' weapon_name=weapon.weapon_name %}">
                            <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }}" class="img-fluid custom-image-size">
                        </a>
                    </div>
                    <link rel="stylesheet" href="{% static 'style.css' %}">
                    {% endfor %}
                </div>
            </div>
            
        </div>
    </div>       
</body>
</html>

dataground/templates/weapon_analysis_detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    {% include 'navbar.html' %}
    <link rel="stylesheet" href="{% static 'profile.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        .table-two-cols, .table-four-cols {
            width: 100%;
        }
        .table-two-cols th, .table-two-cols td {
            width: 50%;
        }
        .table-four-cols th, .table-four-cols td {
            width: 25%;
        }
        .col-lg-8 {
            height: 100%;
            margin-top: 0;
            justify-content: center;
            align-items: center;    
        }
        body {
            font-family: SB;
        }
    </style>
</head>
<body>
    <div class="row justify-content-center">
        <div class="col-lg-8 bg-white p-4">
            <div style="background-color: rgb(85, 85, 85); color: white; padding: 10px; background-color: #8e8e8e; margin-right: 5px; margin-bottom: 5px; font-size: 24px; font-weight: bold; margin-top: -24px; margin-left: -24px; margin-right: -24px; text-shadow: -2px 0 black, 0 2px black, 2px 0 black, 0 -2px black;">{{weapon.weapon_tier}} 티어</div>
            <a href="javascript:history.back()" class="btn btn-secondary mb-3" style="position: absolute; right: 30px; top: 9px;">← 무기 목록</a>
            
            <div class="row justify-content-center align-items-center" style="margin-top: 30px; margin-bottom: 30px;">
                {% with weapon_obj=weapon %}
                <div class="col-lg-4">
                    
                    <img src="{% static 'weapons/'|add:weapon.weapon_name|add:'.JPG' %}" alt="{{ weapon.weapon_name }} 무기 이미지" style="max-width: 100%; max-height: 100%;">               
            </div>
                <div class="col-lg-8">
                    <div class="container">
                        <h2><b>무기상성</b></h2>
                        <table class="table table-bordered table-four-cols" style="width: 100%;">
                            <!-- 테이블 내용은 동일하게 유지 -->
                        <thead>
                            <tr>
                                <th colspan="2" style="font-size: 20px;">상대하기 쉬운 무기 TOP3</th>
                                <th colspan="2" style="font-size: 20px;">상대하기 어려운 무기 TOP3</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>무기</th>
                                <th>승률</th>
                                <th>무기</th>
                                <th>승률</th>
                            </tr>
                            <tr>
                                <th>{{ weapon_obj.first_easy_weapon }}</th>
                                <td>{{ weapon_obj.first_easy_percent|floatformat:2 }}%</td>
                                <th>{{ weapon_obj.first_hard_weapon }}</th>
                                <td>{{ weapon_obj.first_hard_percent|floatformat:2 }}%</td>
                            </tr>
                            <tr>
                                <th>{{ weapon_obj.second_easy_weapon }}</th>
                                <td>{{ weapon_obj.second_easy_percent|floatformat:2 }}%</td>
                                <th>{{ weapon_obj.second_hard_weapon }}</th>
                                <td>{{ weapon_obj.second_hard_percent|floatformat:2 }}%</td>
                            </tr>
                            <tr>
                                <th>{{ weapon_obj.third_easy_weapon }}</th>
                                <td>{{ weapon_obj.third_easy_percent|floatformat:2 }}%</td>
                                <th>{{ weapon_obj.third_hard_weapon }}</th>
                                <td>{{ weapon_obj.third_hard_percent|floatformat:2 }}%</td>
                            </tr>
                        </tbody>
                    </table>            
                </div>
            </div>
            {% endwith %}
        </div>

          <div class="row">
            <div class="col-lg-10 offset-lg-1">
              <h2><b><div class="tier1-header">Parts 선호도</div></b></h2>
              {% for part_type in weapon_parts_type_all %}
              {% if part_type.parts|length > 0 %}
                <div class="category-section">
                  <div class="part-type-name"><b>{{ part_type.name }}</b></div>
                  <div class="row">
                    {% for part in part_type.parts %}
                      <div class="col-lg-2">
                        <div class="part-info">
                          <img src="{% static 'parts/'|add:part.parts_name|add:'.JPG' %}" alt="{{ part.parts_name }}" style="width: 100%;">
                          <p class="part-utilization"><b>사용률: {{ part.utilization_rate }}%</b></p>
                        </div>
                      </div>
                      {% if forloop.counter|divisibleby:6 %}
                        <div class="w-100"></div>
                      {% endif %}
                    {% endfor %}
                  </div>
                </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
          
          
            {% with weapon_image_path=graph_url %}
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                  <div class="distance-section">
                    <div class="text-center">
                        <h2 class="distance-name">거리에 따른 킬 퍼포먼스</h2>
                        <img src="{{ weapon_image_url }}" alt="{{ weapon.weapon_name }} 무기 거리분석" class="img-fluid weapon-image">
                    </div>
                    </div>
                </div>
            </div>
            {% endwith %}
        </div>
    </div>
</body>
</html>